const lilypond_spellings = {
    "a_acoustic": "cs ds e fs g a b",
    "as_acoustic": "c d e f g af bf",
    "b_acoustic": "cs ds es fs gs a b",
    "c_acoustic": "c d e fs g a bf",
    "cs_acoustic": "cf df ef f g af bf",
    "d_acoustic": "c d e fs gs a b", 
    "ds_acoustic": "c df ef f g a bf",
    "e_acoustic": "cs d e fs gs as b",
    "f_acoustic": "c d ef f g a b",
    "fs_acoustic": "cs ds e fs gs as bs",
    "g_acoustic": "cs d e f g a b",
    "gs_acoustic": "c d ef f gf af bf",

    "a_diatonic": "cs d e fs gs a b", 
    "as_diatonic": "c d ef f g a bf",
    "b_diatonic": "cs ds e fs gs as b",
    "c_diatonic": "c d e f g a b",
    "cs_diatonic": "c df ef f gf af bf",
    "d_diatonic": "cs d e fs g a b",
    "ds_diatonic": "c d ef f g af bf",
    "e_diatonic": "cs ds e fs gs a b",
    "f_diatonic": "c d e f g a bf",
    "fs_diatonic": "cs ds es fs gs as b",
    "g_diatonic": "c d e fs g a b",
    "gs_diatonic": "c df ef f g af bf",

    "a_harmonic_major": "cs d e f gs a b",
    "as_harmonic_major": "c d ef f gf a bf",
    "b_harmonic_major": "cs ds e fs g as b",
    "c_harmonic_major": "c d e f g af b",
    "cs_harmonic_major": "c df ef f gf af bff",
    "d_harmonic_major": "cs d e fs g a bf",
    "ds_harmonic_major": "cf d ef f g af bf",
    "e_harmonic_major": "c ds e fs gs a b",
    "f_harmonic_major": "c df e f g a bf",
    "fs_harmonic_major": "cs d es fs gs as b",
    "g_harmonic_major": "c d ef fs g a b",
    "gs_harmonic_major": "c df ef ff g af bf",

    "a_harmonic_minor": "c d e f gs a b",
    "as_harmonic_minor": "c df ef f gf a bf",
    "b_harmonic_minor": "cs d e fs g as b",
    "c_harmonic_minor": "c d ef f g af b",
    "cs_harmonic_minor": "c df ef ff gf af bff",
    "d_harmonic_minor": "cs d e f g a bf",
    "ds_harmonic_minor": "cf d ef f gf af bf",
    "e_harmonic_minor": "c ds e fs g a b",
    "f_harmonic_minor": "c df e f g af bf",
    "fs_harmonic_minor": "cs d es fs gs a b",
    "g_harmonic_minor": "c d ef fs g a bf",
    "gs_harmonic_minor": "cf df ef ff g af bf",

    "whole_tone_1": "c d e fs af bf",
    "whole_tone_2": "cs ef f g a b",

    "octatonic_1": "c cs ds e fs g a bf",
    "octatonic_2": "cs d e f g gs as b",
    "octatonic_3": "c d ef f fs gs a b",

    "hexatonic_1": "c df e f gs a",
    "hexatonic_2": "cs d f gf a as",
    "hexatonic_3": "d ef fs g as b",
    "hexatonic_4": "c ds e g gs b"
}
